version: '2'

services:
  reverseproxy:
    image: reverseproxy
    ports:
      - 8080:8080
      - 8081:8081
    restart: always

  node:
    depends_on:
      - reverseproxy
    image: node111
    restart: "no"

  apache:
    depends_on:
      - reverseproxy
    image: httpd:alpine
    restart: always